# Generated by Django 5.2 on 2025-04-11 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicante',
            name='tratamiento',
        ),
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('D', 'Divorciado')], default='S', max_length=10),
        ),
        migrations.AddField(
            model_name='practicante',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=10),
        ),
        migrations.AddField(
            model_name='practicante',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='status',
            field=models.CharField(choices=[('preparation', 'Preparación'), ('in-progress', 'En Progreso'), ('not-done', 'No Realizado'), ('on-hold', 'En Espera'), ('stopped', 'Parado'), ('completed', 'Completado'), ('entered-in-error', 'Con Errores'), ('unknown', 'Desconocido')], default='preparation', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=10),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='diente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica.diente'),
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica.paciente'),
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='practicante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica.practicante'),
        ),
    ]
