# Generated by Django 5.2 on 2025-06-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0006_rename_coidad_paciente_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('U', 'Desconocido')], default='U', max_length=10),
        ),
    ]
