# Generated by Django 5.2 on 2025-06-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0007_alter_paciente_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='diente',
            name='designacion_iso',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diente',
            name='designacion_universal',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
