# Generated by Django 5.2 on 2025-06-28 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0008_diente_designacion_iso_diente_designacion_universal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimientoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('text', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='text',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='codigo',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinica.procedimientocatalogo'),
        ),
    ]
