# Generated by Django 5.2 on 2025-06-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0009_procedimientocatalogo_procedimiento_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimiento',
            name='codigo',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='procedimientocatalogo',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
