# Generated by Django 5.2 on 2025-06-28 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0010_alter_procedimiento_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimiento',
            name='catalogo',
        ),
        migrations.RemoveField(
            model_name='procedimiento',
            name='text',
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica.procedimientocatalogo'),
        ),
    ]
