# Generated by Django 5.2 on 2025-06-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0011_remove_procedimiento_catalogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimiento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
