# Generated by Codex on 2026-07-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0014_seed_reference_catalogs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="id",
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
