# Generated by Codex on 2026-07-05

import uuid

from django.db import migrations, models


def randomize_existing_procedure_ids(apps, schema_editor):
    table_name = schema_editor.quote_name("clinica_procedimiento")

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"SELECT id FROM {table_name}")
        old_ids = [row[0] for row in cursor.fetchall()]

        assigned_ids = set()
        for old_id in old_ids:
            new_id = uuid.uuid4().hex
            while new_id in assigned_ids:
                new_id = uuid.uuid4().hex

            assigned_ids.add(new_id)
            cursor.execute(
                f"UPDATE {table_name} SET id = %s WHERE id = %s",
                [new_id, old_id],
            )


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0015_alter_paciente_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procedimiento",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RunPython(randomize_existing_procedure_ids, migrations.RunPython.noop),
    ]
